from quart import current_app
from semantic_kernel.agents import AzureAIAgent, AzureAIAgentThread
from semantic_kernel.contents.chat_message_content import ChatMessageContent
from semantic_kernel.contents.utils.author_role import AuthorRole